### ISSUE TITLE
qat.py fails with error "Dataset not found ⚠️, missing paths ['/datasets/coco/val2017.txt']"

### ISSUE THREAD

**Issue by nikcleju** [levipereira/yolov9-qat#11]
I'm following the steps exactly as detailed in the README.md. When reaching the quantization step, the line 

```
python3 qat.py quantize --weights yolov9-c-converted.pt  --name yolov9_qat --exist-ok
```

fails with error "Dataset not found ⚠️, missing paths ['/datasets/coco/val2017.txt']".

It seems that the default `coco.yaml` comes with the path `path: ../datasets/coco  # dataset root dir`, while the dataset is actually in `/yolov9/coco`

Replacing with `path: /yolov9/coco  # dataset root dir` in `coco.yaml` fixes this.

**Comment by levipereira** [comment]
This simple adjustment is indeed necessary since this configuration comes from the original YOLOv9 repository.
