### ISSUE TITLE
How to deploy yolov9-qat model using C++ TensorRT?

### ISSUE THREAD

**Issue by demuxin** [levipereira/yolov9-qat#8]
Hi, levipereira:
Thank you for your contribution, I want to deploy yolov9-qat model using C++ TensorRT. 
Can you provide some reference materials?

**Comment by levipereira** [comment]
The YOLOv9 QAT model utilizes Q/DQ nodes, simplifying the process of build the engine file significantly. Simply adding the flags --int8 --fp16 is sufficient to build the model. The remaining process is identical to non-QAT models. There are several TensorRT C++ projects with YOLOv9 on GitHub ready to use. The only difference is that during engine building, you specify support for INT8.

https://github.com/spacewalk01/tensorrt-yolov9

**Comment by demuxin** [comment]
Thank you very much.

**Comment by demuxin** [comment]
@levipereira , I have deployed yolov9-qat model using C++ tensort, But I find the inference time is same comparing with fp16.
The modification I made on the fp16 code was simply to add a this:
```
config->setFlag(nvinfer1::BuilderFlag::kINT8);
```
i.e. I set both fp16 and int8:
```
config->setFlag(nvinfer1::BuilderFlag::kINT8);
config->setFlag(nvinfer1::BuilderFlag::kFP16);
```
